sudo: required

matrix:
   include:
      - os: osx
        before_install: brew install python3
      - os: linux
        before_install: sudo apt install python3-pip

env:
   - CIBW_SKIP="cp27-* cp33-*"
   - HOMEBREW_NO_AUTO_UPDATE=1

services:
   - docker

script:
  - python3 -m pip install cibuildwheel==0.6.0 --user
  - cibuildwheel --output-dir wheelhouse

