sudo: reuqired
language: python

python:
   - "3.4"
   - "3.5"
   - "3.6"
   - "3.7-dev"

os:
   - linux
   - osx

env:
   - CIBW_SKIP="cp27-* cp33-*"

services:
   - docker

script:
  - python3 -m pip install cibuildwheel==0.6.0
  - cibuildwheel --output-dir wheelhouse
