sudo: required
language: python

os:
   - linux
   - osx

env:
   - CIBW_SKIP="cp27-* cp33-*"

services:
   - docker

script:
  - python -m pip install cibuildwheel==0.6.0
  - cibuildwheel --output-dir wheelhouse

matrix:
   include:
      - os: osx
        before_install: brew install python3
      - os: linux
        before_install: sudo apt install python3-pip
