environment:
   matrix:
      - PYTHON: "C:\\Python34-x64"
        PYTHON_VERSION: "3.4.x"
        PYTHON_ARCH: "64"
build_script:
   - "%PYTHON%\\python3.exe -m pip install wheel cibuildwheel==0.6.0"
   - "%PYTHON%\\python3.exe -m cibuildwheel --output-dir wheelhouse"
artifacts:
   - path: "wheelhouse\\*.whl"
     name: Wheels
