name: rtcloud
channels:
  - brainiak
  - conda-forge
  - default
dependencies:
  - click
  - ipython
  - requests
  - pathos
  - tqdm
  - watchdog
  - flask
  - matplotlib
  - pandas
  - nilearn
  - numpy
  - scipy==0.19.1
  - pybind11
  - cython
  - pika
  - pip:
    - brainiak==0.4.0
    - flask_session
    - ipywidgets
    - jupyter_contrib_nbextensions
    - jupyter
    - binaryornot
    - cfncluster
    - clickutil
